theme: jekyll-theme-minimal
description: I'm a computer scientist. My passions are games, puzzles (mostly the ones involving math), music, and story-telling.
logo: /assets/img.JPG

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
